import os
import requests
from fastapi import FastAPI, Request, HTTPException, BackgroundTasks
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from langfuse.langchain import CallbackHandler

from review_lab.agents.graph import build_review_graph

app = FastAPI(
    title="Review Lab - Multi-Agent AI Code Reviewer",
    description="LangGraph powered supervisor agent for automated PR reviews."
)

# FIX: CORS middleware was missing entirely -- the browser blocks any
# cross-origin request without it, so the Review Lab tab in the UI
# (served from :5173 or :3000) could never reach this API directly.
app.add_middleware(
    CORSMiddleware,
    allow_origins=os.getenv(
        "CORS_ALLOWED_ORIGINS",
        "http://localhost:5173,http://localhost:3000"
    ).split(","),
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Initialize the LangGraph workflow
review_graph = build_review_graph()

@app.get("/health")
def health_check():
    """Confirms the laboratory API is up and running."""
    return {"status": "healthy", "service": "review-lab"}

class ReviewRequest(BaseModel):
    code_snippet: str
    pr_url: str | None = None

def post_github_comment(pr_comments_url: str, comment_body: str):
    """Posts the final AI review back to the GitHub PR."""
    token = os.getenv("GITHUB_TOKEN")
    if not token:
        print("⚠️ GITHUB_TOKEN not set. Skipping actual PR comment posting.")
        return
        
    headers = {
        "Authorization": f"token {token}",
        "Accept": "application/vnd.github.v3+json"
    }
    response = requests.post(pr_comments_url, json={"body": comment_body}, headers=headers)
    if response.status_code != 201:
        print(f"❌ Failed to post comment: {response.text}")

@app.post("/review")
async def review_code(request: ReviewRequest):
    """
    Direct endpoint to submit code for AI review.
    Integrates Langfuse for deep observability of the agent routing.
    """
    # 1. Initialize Langfuse Callback Handler for Observability (RV-07)
    langfuse_handler = CallbackHandler()
    
    initial_state = {
        "messages": [],
        "code_snippet": request.code_snippet,
        "next_agent": "supervisor",
        "final_review": ""
    }
    
    try:
        # 2. Execute the LangGraph workflow with tracing
        print(f"🚀 Starting multi-agent review process...")
        result = review_graph.invoke(
            initial_state, 
            config={"callbacks": [langfuse_handler]}
        )
        
        final_review_markdown = result.get("final_review", "No review generated.")
        return {"status": "success", "review": final_review_markdown}
        
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Review pipeline failed: {str(e)}")

@app.post("/webhook/github")
async def github_webhook(request: Request, background_tasks: BackgroundTasks):
    """
    GitHub Webhook endpoint (RV-06). Listens for 'pull_request' events,
    extracts the diff, and runs the review pipeline in the background.
    """
    payload = await request.json()
    
    # Only trigger on newly opened Pull Requests
    if payload.get("action") == "opened" and "pull_request" in payload:
        pr_data = payload["pull_request"]
        diff_url = pr_data["diff_url"]
        comments_url = pr_data["comments_url"]
        
        # Fetch the actual code diff from GitHub
        diff_response = requests.get(diff_url)
        code_diff = diff_response.text
        
        # We don't want to block the webhook response (GitHub expects a fast 200 OK)
        # So we process the LangGraph AI heavy-lifting in the background.
        background_tasks.add_task(process_pr_background, code_diff, comments_url)
        
        return {"status": "accepted", "message": "PR review task queued."}
        
    return {"status": "ignored", "message": "Not an opened PR event."}

def process_pr_background(code_diff: str, comments_url: str):
    """Background task to run the agents and post the result to GitHub."""
    langfuse_handler = CallbackHandler()
    initial_state = {
        "messages": [],
        "code_snippet": code_diff,
        "next_agent": "supervisor",
        "final_review": ""
    }
    
    try:
        result = review_graph.invoke(initial_state, config={"callbacks": [langfuse_handler]})
        final_review = result.get("final_review")
        
        # Append an AI signature
        final_review += "\n\n---\n*🤖 This review was generated by the LangGraph Multi-Agent LLMOps Pipeline.*"
        
        # Post back to GitHub
        post_github_comment(comments_url, final_review)
    except Exception as e:
        print(f"Background PR processing failed: {e}")